// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Grid struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Home     *Position `json:"home"`
	RowSpace float64   `json:"row_space"`
	ColSpace float64   `json:"col_space"`
	NRows    int       `json:"n_rows"`
	NCols    int       `json:"n_cols"`
}

type Matrix struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Grids []*Grid `json:"grids"`
}

type NewGrid struct {
	MatrixID string       `json:"matrixId"`
	Name     string       `json:"name"`
	Home     *NewPosition `json:"home"`
	RowSpace float64      `json:"rowSpace"`
	ColSpace float64      `json:"colSpace"`
	NRows    int          `json:"n_rows"`
	NCols    int          `json:"n_cols"`
}

type NewMatrix struct {
	Name  string     `json:"name"`
	Grids []*NewGrid `json:"grids,omitempty"`
}

type NewNode struct {
	Grid     string `json:"grid"`
	Position string `json:"position"`
	Aspirate *bool  `json:"aspirate,omitempty"`
}

type NewPosition struct {
	X float64 `json:"X"`
	Y float64 `json:"Y"`
	Z float64 `json:"Z"`
}

type NewRecipe struct {
	Name      string         `json:"name"`
	MatrixID  string         `json:"matrixId"`
	Transfers []*NewTransfer `json:"transfers,omitempty"`
}

type NewTransfer struct {
	SampleID string   `json:"sampleId"`
	Name     *string  `json:"name,omitempty"`
	Group    *string  `json:"group,omitempty"`
	Source   *NewNode `json:"source"`
	Dest     *NewNode `json:"dest"`
	Volume   float64  `json:"volume"`
}

type Node struct {
	Grid     string `json:"grid"`
	Position string `json:"position"`
	Aspirate bool   `json:"aspirate"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

type Recipe struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Matrix    *Matrix     `json:"matrix"`
	Transfers []*Transfer `json:"transfers"`
	Download  string      `json:"download"`
}

type Transfer struct {
	ID       string  `json:"id"`
	SampleID string  `json:"sampleId"`
	Name     *string `json:"name,omitempty"`
	Group    *string `json:"group,omitempty"`
	Source   *Node   `json:"source"`
	Dest     *Node   `json:"dest"`
	Volume   float64 `json:"volume"`
}
